samplesheet_header_rows: 10

sesame_params:
  array_type: "EPIC"
  prep_method: "QCDPB"

idat_dir:  "/home/daisy.fu/bbc-secondary/research/NEPK_2022_EPIC_910/raw_data"  ## the direcdtory where the idat files are stored, it can be absolute too 

modules:
  R: bbc2/R/alt/R-4.4.0-setR_LIBS_USER
